# Generated by Django 4.1.7 on 2023-02-22 09:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast_Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(default="Post something!! (xc", max_length=500),
                ),
                ("date_of_blog", models.DateField(default=datetime.date.today)),
                ("blog_text", models.TextField(default="Must be something")),
                (
                    "blog_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
