# Generated by Django 4.1.7 on 2023-02-22 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Podcast_Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(default="Post something!! (xc", max_length=500),
                ),
                ("time_of_blog", models.DateTimeField(default=datetime.datetime.now)),
                ("blog_text", models.TextField(default="Must be something")),
            ],
        ),
    ]
