# Generated by Django 4.1.7 on 2023-02-22 13:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("podcast_blog", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_text", models.TextField()),
                (
                    "time_of_comment",
                    models.DateTimeField(default=datetime.datetime.now),
                ),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="podcast_blog.podcast_blog",
                    ),
                ),
                (
                    "comment_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
