# Generated by Django 4.1.7 on 2023-02-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("podcast_blog", "0004_podcast_blog_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="comment_text",
            field=models.TextField(help_text="Enter your comment here."),
        ),
    ]
