# Generated by Django 4.1.7 on 2023-03-09 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("is_live", models.BooleanField(default=False)),
                ("is_recorded", models.BooleanField(default=False)),
                (
                    "recording_file",
                    models.FileField(
                        blank=True, null=True, upload_to="podcast_recordings/"
                    ),
                ),
                ("broadcast_url", models.URLField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_podcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invited_to_podcasts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
