# Generated by Django 4.1.7 on 2023-02-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=100)),
                ("country_code", models.CharField(max_length=3)),
            ],
        ),
    ]
